# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sampling_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sampling_service.proto\"\xea\x01\n\x0fSamplingRequest\x12,\n\x0fsampling_method\x18\x01 \x01(\x0e\x32\x13.SamplingMethodType\x12$\n\x0b\x66ile_format\x18\x02 \x01(\x0e\x32\x0f.FileFormatType\x12$\n\rsampling_conf\x18\x03 \x01(\x0b\x32\r.SamplingConf\x12$\n\x0b\x66ormat_conf\x18\x04 \x01(\x0b\x32\x0f.FileFormatConf\x12\x12\n\ninput_path\x18\x05 \x01(\t\x12\x13\n\x0boutput_path\x18\x06 \x01(\t\x12\x0e\n\x06job_id\x18\x07 \x01(\t\"\x1f\n\rCancelRequest\x12\x0e\n\x06job_id\x18\x07 \x01(\t\"/\n\x0e\x43\x61ncelResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xaf\x01\n\x10SamplingResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12,\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1e.SamplingResponse.ResponseData\x1aN\n\x0cResponseData\x12(\n\x0eparent_request\x18\x01 \x01(\x0b\x32\x10.SamplingRequest\x12\x14\n\x0csampled_path\x18\x02 \x01(\t\"#\n\x04\x64ict\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x85\x01\n\x0cSamplingConf\x12\x10\n\x08\x66raction\x18\x01 \x01(\t\x12\x18\n\x10with_replacement\x18\x02 \x01(\x08\x12\x0c\n\x04seed\x18\x03 \x01(\r\x12\x16\n\x0estratified_key\x18\x04 \x01(\t\x12\r\n\x05\x63ount\x18\x05 \x01(\r\x12\x14\n\x0csampling_col\x18\x06 \x03(\t\"2\n\x0e\x46ileFormatConf\x12\x13\n\x0bwith_header\x18\x01 \x01(\x08\x12\x0b\n\x03sep\x18\x02 \x01(\t*\x80\x01\n\x12SamplingMethodType\x12\x12\n\x0eUNKNOWN_METHOD\x10\x00\x12\x1a\n\x16RANDOM_SAMPLING_METHOD\x10\x01\x12\x1e\n\x1aSTRATIFIED_SAMPLING_METHOD\x10\x02\x12\x1a\n\x16SIMPLE_SAMPLING_METHOD\x10\x03*9\n\x0e\x46ileFormatType\x12\x12\n\x0eUNKNOWN_FORMAT\x10\x00\x12\x13\n\x0f\x46ILE_FORMAT_CSV\x10\x01\x32|\n\x14SparkSamplingService\x12\x34\n\x0bSamplingJob\x12\x10.SamplingRequest\x1a\x11.SamplingResponse\"\x00\x12.\n\tCancelJob\x12\x0e.CancelRequest\x1a\x0f.CancelResponse\"\x00\x62\x06proto3')

_SAMPLINGMETHODTYPE = DESCRIPTOR.enum_types_by_name['SamplingMethodType']
SamplingMethodType = enum_type_wrapper.EnumTypeWrapper(_SAMPLINGMETHODTYPE)
_FILEFORMATTYPE = DESCRIPTOR.enum_types_by_name['FileFormatType']
FileFormatType = enum_type_wrapper.EnumTypeWrapper(_FILEFORMATTYPE)
UNKNOWN_METHOD = 0
RANDOM_SAMPLING_METHOD = 1
STRATIFIED_SAMPLING_METHOD = 2
SIMPLE_SAMPLING_METHOD = 3
UNKNOWN_FORMAT = 0
FILE_FORMAT_CSV = 1


_SAMPLINGREQUEST = DESCRIPTOR.message_types_by_name['SamplingRequest']
_CANCELREQUEST = DESCRIPTOR.message_types_by_name['CancelRequest']
_CANCELRESPONSE = DESCRIPTOR.message_types_by_name['CancelResponse']
_SAMPLINGRESPONSE = DESCRIPTOR.message_types_by_name['SamplingResponse']
_SAMPLINGRESPONSE_RESPONSEDATA = _SAMPLINGRESPONSE.nested_types_by_name['ResponseData']
_DICT = DESCRIPTOR.message_types_by_name['dict']
_SAMPLINGCONF = DESCRIPTOR.message_types_by_name['SamplingConf']
_FILEFORMATCONF = DESCRIPTOR.message_types_by_name['FileFormatConf']
SamplingRequest = _reflection.GeneratedProtocolMessageType('SamplingRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGREQUEST,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:SamplingRequest)
  })
_sym_db.RegisterMessage(SamplingRequest)

CancelRequest = _reflection.GeneratedProtocolMessageType('CancelRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANCELREQUEST,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:CancelRequest)
  })
_sym_db.RegisterMessage(CancelRequest)

CancelResponse = _reflection.GeneratedProtocolMessageType('CancelResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANCELRESPONSE,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:CancelResponse)
  })
_sym_db.RegisterMessage(CancelResponse)

SamplingResponse = _reflection.GeneratedProtocolMessageType('SamplingResponse', (_message.Message,), {

  'ResponseData' : _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLINGRESPONSE_RESPONSEDATA,
    '__module__' : 'sampling_service_pb2'
    # @@protoc_insertion_point(class_scope:SamplingResponse.ResponseData)
    })
  ,
  'DESCRIPTOR' : _SAMPLINGRESPONSE,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:SamplingResponse)
  })
_sym_db.RegisterMessage(SamplingResponse)
_sym_db.RegisterMessage(SamplingResponse.ResponseData)

dict = _reflection.GeneratedProtocolMessageType('dict', (_message.Message,), {
  'DESCRIPTOR' : _DICT,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:dict)
  })
_sym_db.RegisterMessage(dict)

SamplingConf = _reflection.GeneratedProtocolMessageType('SamplingConf', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGCONF,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:SamplingConf)
  })
_sym_db.RegisterMessage(SamplingConf)

FileFormatConf = _reflection.GeneratedProtocolMessageType('FileFormatConf', (_message.Message,), {
  'DESCRIPTOR' : _FILEFORMATCONF,
  '__module__' : 'sampling_service_pb2'
  # @@protoc_insertion_point(class_scope:FileFormatConf)
  })
_sym_db.RegisterMessage(FileFormatConf)

_SPARKSAMPLINGSERVICE = DESCRIPTOR.services_by_name['SparkSamplingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLINGMETHODTYPE._serialized_start=749
  _SAMPLINGMETHODTYPE._serialized_end=877
  _FILEFORMATTYPE._serialized_start=879
  _FILEFORMATTYPE._serialized_end=936
  _SAMPLINGREQUEST._serialized_start=27
  _SAMPLINGREQUEST._serialized_end=261
  _CANCELREQUEST._serialized_start=263
  _CANCELREQUEST._serialized_end=294
  _CANCELRESPONSE._serialized_start=296
  _CANCELRESPONSE._serialized_end=343
  _SAMPLINGRESPONSE._serialized_start=346
  _SAMPLINGRESPONSE._serialized_end=521
  _SAMPLINGRESPONSE_RESPONSEDATA._serialized_start=443
  _SAMPLINGRESPONSE_RESPONSEDATA._serialized_end=521
  _DICT._serialized_start=523
  _DICT._serialized_end=558
  _SAMPLINGCONF._serialized_start=561
  _SAMPLINGCONF._serialized_end=694
  _FILEFORMATCONF._serialized_start=696
  _FILEFORMATCONF._serialized_end=746
  _SPARKSAMPLINGSERVICE._serialized_start=938
  _SPARKSAMPLINGSERVICE._serialized_end=1062
# @@protoc_insertion_point(module_scope)
