"""
app所需要的环境变量
"""

DEBUG_PORT = 8000
QUERY_PORT = 8000
SAMPLING_JOB_PORT = 8001
STATISTICS_JOB_PORT = 8002

QUERY_PARALLEL = 2
SAMPLING_PARALLEL = 3
STATISTICS_PARALLEL = 4

DEBUG = True
DB_USERNAME = 'root'
DB_NAME = 'sampling'
DB_HOST = 'localhost'
DB_PASSWORD = 'baobao'
