### 配置的全局变量位于文件夹下的http-client.env.json

### Hello World Test
GET http://{{host}}:{{port}}
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

###
POST http://{{host}}:{{port}}
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

###
POST http://{{host}}:{{port}}/v1/sampling/simplejob/
Accept: application/json

< requestbody/simple-random-sampling.json

###
POST http://{{host}}:{{port}}/v1/sampling/simplejob/
Accept: application/json

< requestbody/stratified-sampling.json

###
POST http://{{host}}:{{port}}/v1/sampling/mljob/
Accept: application/json

< requestbody/smote-sampling.json

###
POST http://{{host}}:{{port}}/v1/sampling/query/job/
Accept: application/json

< requestbody/query.json

###
POST http://{{host}}:{{port}}/v1/sampling/query/list/
Accept: application/json

< requestbody/list.json

###
POST http://{{host}}:{{port}}/v1/statistics/
Accept: application/json

< requestbody/statistics.json
